"""added created_at & updated_at

Revision ID: 11032532fac0
Revises: 2bdef8b040bd
Create Date: 2019-04-22 22:16:29.670987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11032532fac0'
down_revision = '2bdef8b040bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('posts', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_posts_created_at'), 'posts', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posts_created_at'), table_name='posts')
    op.drop_column('posts', 'updated_at')
    op.drop_column('posts', 'created_at')
    # ### end Alembic commands ###
